### PR TITLE
Colorpicker feature idea: adding quote characters to the string copied.

### PR DESCRIPTION
**Pull request by villares**
Do you think this is a good idea?

Also, I have changed the text on the selector dialog, but for some reason my git is ignoring that change:
image

How bad is it to change this "vendorized" color selector?

### CODE REVIEW

**Comment by villares** [comment]
The dialog changes, with a PT translation and other minor tweaks, if you care to have a look, are here:
https://gist.github.com/villares/970145e83bcf0400b1b6571031e1208c

**Comment by tabreturn** [comment]
I'm thinking: avoid forcing quotes on the hex code? The PDE doesn't do this, and it could be annoying if one is trying to replace an existing color (double-click in the Thonny editor selects everything *within* the quotes). I like the label change, though. Maybe we just merge that?

**Comment by villares** [comment]
You have a good point, we could have a compromise: a button with quotes and another without... 

There is a challenge with modeless of avoid multiple panels... I'm not sure how critical is that.

**Comment by villares** [comment]
So, let's close this. We'll need a PR here later to remove the `pyperclip` code, as we move it to the modeless dialog...
I'll open a PR at the other repo now!.

**Pull request closed without merging**
