### PR TITLE
Modeless colorpicker

### PR DESCRIPTION
**Pull request by villares**
The "for working with a modeless color selector window" is related to the thonny-py5mode changes that I will propose at the other repo (thonny-py5mode-tkcolorpicker)

### CODE REVIEW

**Comment by villares** [comment]
Sorry @tabreturn, I'm terrible with git.
The "adding quotes" commits where not supposed to be here...

**Comment by tabreturn** [comment]
@villares -- you'll have to add a pull-request for your changes to the sub-module (https://github.com/tabreturn/thonny-py5mode-tkcolorpicker) so that the code here can import it

**Comment by villares** [comment]
> @villares -- you'll have to add a pull-request for your changes to the sub-module (https://github.com/tabreturn/thonny-py5mode-tkcolorpicker) so that the code here can import it

here: https://github.com/tabreturn/thonny-py5mode-tkcolorpicker/pull/2

**Comment by villares** [comment]
Cheers @tabreturn! Will the colorpicker be updated in the next release?

On my fork I get this, and I quite like it:
image

**Pull request merged**
